title: "Carlos NoCode"
email: contacto@carlosnocode.com
timezone: America/Merida
baseurl: "" # ← importante: vacío para dominios personalizados
url: "https://carlosnocode.com"
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: carlos
paginate: 10
disqus: "" # puedes poner tu identificador si vas a usar Disqus
locale: es_MX
lang: es_MX
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: "" # agrega tu ID si vas a usar Google Analytics

# Authors
authors:
  carlos:
    name: Carlos
    display_name: Carlos NoCode
    avatar: "assets/images/carlos.png" # pon aquí tu imagen de perfil si tienes una
    email: contacto@carlosnocode.com
    web: https://carlosnocode.com
    twitter: https://twitter.com/tuusuario
    description: "Soy Carlos, creador de contenido sobre automatización, herramientas sin código e inteligencia artificial para negocios modernos."

# Social
social:
  instagram: https://www.instagram.com/carlosnocode
  facebook: https://www.facebook.com/people/Carlos-NoCode/61553781673239/
  twitter: https://x.com/CarlosNoCode
  tiktok: https://www.tiktok.com/@carlosnocode_

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
